name: cd

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash -l {0} # Use the login shell that our setup-env action sets up

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
